### ISSUE TITLE
Template does not compile

### ISSUE THREAD

**Issue by thomas-panitz** [duncanturk/haw-hof-bachelor-latex#7]
Template cannot be compiled with Manjaro Linux and the packages texlive-core 2019.52579-1, texlive-latexextra 2019.52575.1, texlive-publishers 2019.52538-1, biber 1:2.13-1.

Thanks.

**Comment by christopher-rossbach** [comment]
thanks for submitting the bug.
What tools are used to compile? What's the error?

**Comment by christopher-rossbach** [comment]
You may be missing some packages. Having `biber` the packages in `texlive-most` installed should work fine on archlinux.
